name: Build ReportAnnotationGUI App

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      artifact-name: ReportAnnotationGUI-windows-build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade setuptools==44.0.0, pip==25.0.1, wheel==0.45.1
          pip install -r requirements.txt
          pip install --no-binary :all: nmslib==2.1.1

      - name: Build with PyInstaller
        run: |
          pyinstaller app.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReportAnnotationGUI-windows-build
          path: dist/ReportAnnotationGUI.exe

  build-macos-intel:
    runs-on: macos-13
    name: Build macOS (Intel)
    outputs:
      artifact-name: ReportAnnotationGUI-macOS-intel-build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'

      - name: Force Intel architecture
        run: |
          echo "Using Intel architecture"
          export ARCHFLAGS="-arch x86_64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade setuptools==44.0.0 pip==25.0.1 wheel==0.45.1
          pip install -r requirements.txt
          pip install --no-binary :all: nmslib==2.1.1

      - name: Build with PyInstaller
        run: |
          pyinstaller app.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReportAnnotationGUI-macOS-intel-build
          path: dist/ReportAnnotationGUI